### ISSUE TITLE
"Your stamina is to low" Should be "Your stamina is too low!" (Exclamation point optional).

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/stamina-attributes#1]
I'm not trying to be pedantic, but the grammatical issue when stamina is too low to perform an attack is kinda bothering me =P.

**Comment by TheRedBrain** [comment]
will be fixed
for now, you can change it using a resource pack :)

**Comment by InputandOutput** [comment]
Alright, what is the proper id for the stamina error message? Is it contained within a lang file?

**Comment by TheRedBrain** [comment]
"hud.message.staminaTooLow"

**Comment by InputandOutput** [comment]
I got it working yay
