### ISSUE TITLE
Stamina Consumption When Drawing a Bow/Loading a Crossbow or Launching a Projectile

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/stamina-attributes#2]
Some suggestions:
1. Drawing a bow will consume stamina at different stages, and holding a drawn bow will periodically consume stamina. The values could be customized. Insufficient stamina results in premature shooting of the bow or inability to completely load a crossbow.
2. Loading a crossbow should take some amount of stamina, though shooting it may not take stamina. Values may also be customized. 
3. Throwable weapons, such as tridents, should also consume stamina. Insufficient stamina results in inability/shortened throw range and lowered damage. Whether the stamina consumption should be tied to a certain weapon or fixed in the config is up to you. 
4. Throwable items, such as ender pearls, eggs, or snowballs, should consume a set amount of stamina, which the value can be changed as a set value or depending on the item. Insufficient stamina results in inability to throw item and/or throwing it by a short distance.

**Comment by TheRedBrain** [comment]
Valid suggestions, added to the list.

Thanks for your feedback!

**Comment by TheRedBrain** [comment]
all features are now implemented (as of version 1.4.0 / 2.4.0)
