### ISSUE TITLE
[Suggestion] Stamina Consumption when taking a hit with a shield

### ISSUE THREAD

**Issue by Eldog02** [TheRedBrain/stamina-attributes#4]
Hi, I really appreciate that your mod implements stamina as a generic attribute, it makes it easy to integrate into other things like Pufferfish's Skills or with KubeJS!

Something that I think about when considering stamina is how it affects combat, and considering shields are one of the most powerful, must-have items in Minecraft that allow you to invalidate almost all damage, I think it would be a fair trade to make holding up a shield, and blocking a hit with a shield, take a configurable amount of stamina, in tune with the rest of the values in the server config.

**Comment by TheRedBrain** [comment]
Hi!

Stamina costs for using items is already on my todo list and shields are one of the main reasons for that.
This will be implemented via an entity attribute.

A stamina cost for actively blocking attacks will most likely not be implemented. I have already done that in another mod called [Overhauled Damage](https://github.com/TheRedBrain/overhauled-damage/blob/1.21/README.md#blocking-and-parrying), which also overhauls shields to offer more engaging gameplay.

Thank you for the feedback and the suggestion!

**Comment by TheRedBrain** [comment]
holding up a shield costing stamina is now implemented (as of version 1.4.0 / 2.4.0)
