### ISSUE TITLE
[Suggestion] Stamina regen options

### ISSUE THREAD

**Issue by MrBeat93** [TheRedBrain/stamina-attributes#6]
Would be nice to have options to edit:
 * How long it takes before the regen starts
 * How much stamina it regen
 
Bonus suggestion:
 * Option to make the run stamina consumption and the regen, update in realtime for a smoother experience

**Comment by TheRedBrain** [comment]
Hi!

All these things are already possible.

1. This is controlled by the "staminaattributes:generic.stamina_regeneration_delay_threshold" entity attribute. When stamina drops below 0, the "staminaattributes:generic.depleted_stamina_regeneration_delay_threshold" is added to the delay. Both values are measured in ticks. 20 ticks = 1 second

2. This is controlled by entity attributes as well. Stamina is regenerated by "staminaattributes:generic.stamina_regeneration" every "staminaattributes:generic.stamina_tick_threshold" ticks.

3. Doing the calculations in real-time is not possible. Minecraft itself does its calculations only 20 times per second. The stamina bar shows stamina value changes not instantly by default, but has a smooth animation. Make sure the option "enable_smooth_animation" is set to true in the client config.

**Comment by MrBeat93** [comment]
Alright. 
How and where can I edit that? 
I thought it was not possible because of the "server.json5" 
There is only "stamina_cost_..." etc

**Comment by TheRedBrain** [comment]
Entity attributes can be changed in game via commands.
See https://minecraft.wiki/w/Attribute

There are also a few mods that can be used to globally change attributes for eg players.
https://modrinth.com/mod/cea or https://modrinth.com/mod/attributesetter (both for 1.20.1)

**Comment by MrBeat93** [comment]
Nice, gonna check that out. Thanks for the help!
